site_name: DRO Circuit Discovery
site_author: Jiahao Zhang

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
